---
- name: populate service facts
  service_facts:

- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  loop:
  - vdsmd.service
  - supervdsmd.service
  - libvirtd.service
  - virt-imageio-daemon.service
  - NetworkManager.service
  when: "item in ansible_facts.services"

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  # libvirtd may not be started automatically on hosts >= 4.4, it will
  # be started by vdsmd if needed.
  - cgconfig.service
  - messagebus.service
  - virt-imageio-daemon.service
  - NetworkManager.service
  - vdsmd.service
  when: "item in ansible_facts.services"
